title: Acc CS/IT Online Tutor
author:
email: your-email@domain.com
description: > # this means to ignore newlines until "show_exerpts:"
  Website to host online tutoring service during the 2020 Novel Coronavirus outbreak
show_excerpts: true # set to true to show excerpts on the homepage
baseurl:

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
sass:
  sass_dir: _sass

permalink: /posts/:title/
texture:
  title: ACC CS/IT Tutoring
  tagline: Developer. Designer
  date_format: "%b %-d, %Y"
  style: purple
  showNav: false
  showPicker: false

  # generate social links in footer
  social_links:
    twitter: accdistrict
    instagram:  accdistrict
    linkedIn: in/thelehhman
    rss: rss
 

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.md

# Build settings
# theme: texture

plugins:
  - jekyll-seo-tag
#  - jekyll-feed